name: Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install latest Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_AVLxcG288EDyGQsKABK9cLeI
          vercel-project-id: prj_2dl4CfWhVu4kfj9bKVxtI3YalWoi
          vercel-args: '--prod'
