name: Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel with latest CLI
        run: npx vercel@latest deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --cwd=${{ github.workspace }}
